name: Build and Upload Pull Request
 
on: 
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, reopened ]

jobs:
  
  build-gui:
    runs-on: windows-latest
    env:
     ACTIONS_ALLOW_UNSECURE_COMMANDS: true
 
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore Dependencies
      run: dotnet restore TwitchDownloaderWPF
    - name: Build Windows GUI
      run: dotnet publish TwitchDownloaderWPF -p:PublishProfile=Windows -p:DebugType=None -p:DebugSymbols=false
    
    - name: Download Ffmpeg To Workspace
      # You may pin to the exact commit or the version.
      # uses: carlosperate/download-file-action@e85e0aa6262f13571d17a4a39687b26981c583dc
      uses: carlosperate/download-file-action@v1.0.3
      with:
        # URL of the file to download
        file-url: https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip
        # New filename to rename the downloaded file
        file-name: ffmpeg.zip
        
    - name: Bundle Ffmpeg
      run: tar xfz ffmpeg.zip --strip-components=1; copy bin/ffmpeg.exe TwitchDownloaderWPF/bin/Release/net6.0-windows/publish/win-x64/ffmpeg.exe
      
    - name: Zip Windows GUI
      uses: vimtor/action-zip@v1
      with:
        files: "TwitchDownloaderWPF/bin/Release/net6.0-windows/publish/win-x64"
        dest: TwitchDownloaderGUI-Windows-x64.zip

    - name: Upload Windows GUI Artifact Asset
      uses: actions/upload-artifact@v3
      with:
        name: TwitchDownloaderGUI-Windows-x64.zip
        path: TwitchDownloaderGUI-Windows-x64.zip

  build-cli:
    runs-on: ubuntu-20.04
    needs: [build-gui]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore Dependencies
      run: dotnet restore TwitchDownloaderCLI
    - name: Build Windows CLI
      run: dotnet publish TwitchDownloaderCLI -p:PublishProfile=Windows -p:DebugType=None -p:DebugSymbols=false
    - name: Build Linux CLI
      run: dotnet publish TwitchDownloaderCLI -p:PublishProfile=Linux -p:DebugType=None -p:DebugSymbols=false
    - name: Build LinuxAlpine CLI
      run: dotnet publish TwitchDownloaderCLI -p:PublishProfile=LinuxAlpine -p:DebugType=None -p:DebugSymbols=false
    - name: Build LinuxArm CLI
      run: dotnet publish TwitchDownloaderCLI -p:PublishProfile=LinuxArm -p:DebugType=None -p:DebugSymbols=false
        
    - name: Zip Windows CLI
      uses: vimtor/action-zip@v1
      with:
        files: TwitchDownloaderCLI/bin/Release/net6.0/publish/Windows/TwitchDownloaderCLI.exe
        dest: TwitchDownloaderCLI-Windows-x64.zip
        
    - name: Zip Linux CLI
      uses: vimtor/action-zip@v1
      with:
        files: TwitchDownloaderCLI/bin/Release/net6.0/publish/Linux/TwitchDownloaderCLI
        dest: TwitchDownloaderCLI-Linux-x64.zip
        
    - name: Zip LinuxAlpine CLI
      uses: vimtor/action-zip@v1
      with:
        files: TwitchDownloaderCLI/bin/Release/net6.0/publish/LinuxAlpine/TwitchDownloaderCLI
        dest: TwitchDownloaderCLI-LinuxAlpine-x64.zip
    
    - name: Zip LinuxArm CLI
      uses: vimtor/action-zip@v1
      with:
        files: TwitchDownloaderCLI/bin/Release/net6.0/publish/LinuxArm/TwitchDownloaderCLI
        dest: TwitchDownloaderCLI-LinuxArm.zip

    - name: Upload Windows CLI Artifact Asset
      uses: actions/upload-artifact@v3
      with:
        name: TwitchDownloaderCLI-Windows-x64.zip
        path: TwitchDownloaderCLI-Windows-x64.zip

    - name: Upload Linux CLI Artifact Asset
      uses: actions/upload-artifact@v3
      with:
        name: TwitchDownloaderCLI-Linux-x64.zip
        path: TwitchDownloaderCLI-Linux-x64.zip

    - name: Upload LinuxAlpine CLI Artifact Asset
      uses: actions/upload-artifact@v3
      with:
        name: TwitchDownloaderCLI-LinuxAlpine-x64.zip
        path: TwitchDownloaderCLI-LinuxAlpine-x64.zip

    - name: Upload LinuxArm CLI Artifact Asset
      uses: actions/upload-artifact@v3
      with:
        name: TwitchDownloaderCLI-LinuxArm.zip
        path: TwitchDownloaderCLI-LinuxArm.zip

  build-cli-mac:
    runs-on: macos-latest
    needs: [build-cli]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore Dependencies
      run: dotnet restore TwitchDownloaderCLI
    - name: Build MacOS CLI
      run: dotnet publish TwitchDownloaderCLI -p:PublishProfile=MacOS -p:DebugType=None -p:DebugSymbols=false
      
    - name: Zip MacOS CLI
      uses: vimtor/action-zip@v1
      with:
        files: TwitchDownloaderCLI/bin/Release/net6.0/publish/MacOS/TwitchDownloaderCLI
        dest: TwitchDownloaderCLI-MacOS-x64.zip

    - name: Upload MacOS CLI Artifact Asset
      uses: actions/upload-artifact@v3
      with:
        name: TwitchDownloaderCLI-MacOS-x64.zip
        path: TwitchDownloaderCLI-MacOS-x64.zip
    

